package io.aime.plugins.protocolhttpclient;

// Util
import java.util.List;

/**
 * The base level of services required for Http Authentication.
 *
 * @see HttpAuthenticationFactory
 *
 * @author Matt Tencati
 * @author K-Zen
 */
public interface HTTPAuthentication {

    /**
     * Gets the credentials generated by the HttpAuthentication object. May
     * return null.
     *
     * @return The credentials value
     */
    public List<String> getCredentials();

    /**
     * Gets the realm used by the HttpAuthentication object during creation.
     *
     * @return The realm value
     */
    public String getRealm();
}
